name: vrAnalysis
channels:
  - numba
  - conda-forge
  - pytorch 
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy==1.24
  - scipy
  - numba
  - matplotlib
  - seaborn
  - ipympl
  - jupyterlab
  - oasis-deconv
  - cvxpy
  # - pytorch
  # - torchvision
  # - torchaudio
  # - pytorch-cuda=12.1
  - pip:
    - numpyencoder
    - pyqt5
    - pyqtgraph
    - pyodbc
    - tqdm
    - pandas
    - h5py
    - napari[all]
    - black
    - ratinabox
    - rastermap
    - optuna