name: vrAnalysis
channels:
  - numba
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - numba
  - matplotlib
  - ipympl
  - jupyterlab
  - oasis-deconv
  - cvxpy
  - pip:
    - natsort
    - numpyencoder
    - pyqt5
    - pyqtgraph
    - pyodbc
    - tqdm
    - pandas
    - h5py
    - napari[all]