name: vrAnalysis
channels:
  - numba
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.24
  - scipy
  - numba
  - matplotlib
  - ipympl
  - jupyterlab
  - oasis-deconv
  - cvxpy
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
    - numpyencoder
    - pyqt5
    - pyqtgraph
    - pyodbc
    - tqdm
    - pandas
    - h5py
    - napari[all]
    - black
    - ratinabox
    - rastermap