"""
Simulation utilities for dimensionality analysis.

This package provides tools for generating synthetic data and performing
matrix operations useful for illustrating dimensionality analysis concepts.
"""

from .generators import (
    CovariancePairConfig,
    CovariancePairGenerator,
    CovarianceGenerator,
    PowerlawDataGenerator,
    RotatedEigenbasisGenerator,
    SharedSpaceConfig,
    SharedSpaceGenerator,
    StimFullConfig,
    StimFullGenerator,
)
from .operators import sqrtm_spd, invsqrtm_spd, geometric_mean_spd, root_sandwich
from .plotting import plot_ellipse
from .placefield_full import (
    PlacefieldFullConfig,
    PlacefieldFullGenerator,
    SmoothGPFieldConfig,
    ThresholdedGPFieldConfig,
    TilburyFieldConfig,
)
from .shared_variance import (
    ATLAS,
    AnalysisProvenance,
    AtlasAnalysisResult,
    AtlasBuild,
    AtlasSpec,
    EmpiricalBlock,
    EmpiricalDiagnostics,
    ModeComparison,
    NeuronSplit,
    PopulationBlock,
    SubspaceGeometry,
    analyze_atlas_case,
    analyze_build,
    build_atlas_case,
    energy_modes,
    get_atlas_spec,
    kappa_modes,
    list_atlas_cases,
    process,
    stimulus_space_energy_modes,
    stimulus_space_kappa_modes,
)
from .utilities import get_orthogonal_direction, generate_orthonormal, find_commute_space, find_commute_space_gated
from .placefield_generator import (
    PlacefieldConfig,
    TilburyConfig,
    SimConfig,
    generate_repeats,
    generate_noise,
    assemble,
    normalize_by_max,
    max_normalizer,
    estimate_spatial_rank,
    peaky_transform,
)
from .estimation_sweep import (
    SweepSpec,
    SweepResults,
    run_manual_sweep,
    run_named_sweep,
    run_param_sweep,
)
from .placefield_analysis import (
    run_neuron_position,
    run_cvpca_stimspace,
    run_cvpca_stimspace_avg,
    run_cvpca_stimspace_stack,
    suggest_config,
    config_from_params,
    run_study,
    plot_placefields,
    plot_example_placefields,
    plot_neuron_position,
    plot_spectra,
    plot_frac_neg,
    plot_component_alignment,
    plot_study,
    print_best_configs,
)

__all__ = [
    "CovariancePairConfig",
    "CovariancePairGenerator",
    "CovarianceGenerator",
    "PowerlawDataGenerator",
    "RotatedEigenbasisGenerator",
    "SharedSpaceConfig",
    "SharedSpaceGenerator",
    "StimFullConfig",
    "StimFullGenerator",
    "sqrtm_spd",
    "invsqrtm_spd",
    "geometric_mean_spd",
    "root_sandwich",
    "plot_ellipse",
    "ATLAS",
    "AnalysisProvenance",
    "AtlasAnalysisResult",
    "AtlasBuild",
    "AtlasSpec",
    "EmpiricalBlock",
    "EmpiricalDiagnostics",
    "ModeComparison",
    "NeuronSplit",
    "PopulationBlock",
    "SubspaceGeometry",
    "PlacefieldFullConfig",
    "PlacefieldFullGenerator",
    "SmoothGPFieldConfig",
    "ThresholdedGPFieldConfig",
    "TilburyFieldConfig",
    "analyze_atlas_case",
    "analyze_build",
    "build_atlas_case",
    "energy_modes",
    "get_atlas_spec",
    "kappa_modes",
    "list_atlas_cases",
    "process",
    "stimulus_space_energy_modes",
    "stimulus_space_kappa_modes",
    "get_orthogonal_direction",
    "generate_orthonormal",
    "find_commute_space",
    "find_commute_space_gated",
    # placefield_generator
    "PlacefieldConfig",
    "TilburyConfig",
    "SimConfig",
    "generate_repeats",
    "generate_noise",
    "assemble",
    "normalize_by_max",
    "max_normalizer",
    "estimate_spatial_rank",
    "peaky_transform",
    # placefield_analysis
    "run_neuron_position",
    "run_cvpca_stimspace",
    "run_cvpca_stimspace_avg",
    "run_cvpca_stimspace_stack",
    "suggest_config",
    "config_from_params",
    "run_study",
    "plot_placefields",
    "plot_example_placefields",
    "plot_neuron_position",
    "plot_spectra",
    "plot_frac_neg",
    "plot_component_alignment",
    "plot_study",
    "print_best_configs",
    # estimation_sweep
    "SweepSpec",
    "SweepResults",
    "run_manual_sweep",
    "run_named_sweep",
    "run_param_sweep",
]
